erDiagram
CatalogView {
    uriorcurie id  
    string name  
    string description  
    uriorcurie ome_model_reference  
    string rembi_alignment  
    string view_sql  
}
ImageOMETiff {
    DataFormat data_format  
    uriorcurie id  
    string name  
    string description  
    uriorcurie ome_model_reference  
    uriorcurie path  
    string rembi_alignment  
}
ImageOMEZarr {
    DataFormat data_format  
    uriorcurie id  
    string name  
    string description  
    uriorcurie ome_model_reference  
    uriorcurie path  
    string rembi_alignment  
}
ImageTIFF {
    DataFormat data_format  
    uriorcurie id  
    string name  
    string description  
    uriorcurie ome_model_reference  
    uriorcurie path  
    string rembi_alignment  
}
Namespace {
    uriorcurie id  
    string name  
    string description  
    WarehouseNamespace namespace  
    uriorcurie ome_model_reference  
    string rembi_alignment  
}
TableAnalyze {
    uriorcurie id  
    string name  
    DataFormat data_format  
    AnalyzedDataRole data_role  
    LifecycleStage lifecycle_stage  
    WarehouseNamespace namespace  
    uriorcurie ome_model_reference  
    string rembi_alignment  
    string description  
    string biological_object  
    string compartment  
    DataFormat format  
    ProfileLevel profile_level  
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    DataTablePrefix table_prefix  
}
TableDerivedMeasurement {
    AnalyzedDataRole data_role  
    uriorcurie id  
    string name  
    string description  
    string biological_object  
    string compartment  
    DataFormat data_format  
    DataFormat format  
    LifecycleStage lifecycle_stage  
    WarehouseNamespace namespace  
    uriorcurie ome_model_reference  
    ProfileLevel profile_level  
    string rembi_alignment  
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    DataTablePrefix table_prefix  
}
TableEmbedding {
    AnalyzedDataRole data_role  
    uriorcurie id  
    string name  
    string description  
    string biological_object  
    string compartment  
    DataFormat data_format  
    DataFormat format  
    LifecycleStage lifecycle_stage  
    WarehouseNamespace namespace  
    uriorcurie ome_model_reference  
    ProfileLevel profile_level  
    string rembi_alignment  
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    DataTablePrefix table_prefix  
}
TableImage {
    WarehouseNamespace namespace  
    string description  
    string biological_object  
    string compartment  
    DataFormat format  
    ProfileLevel profile_level  
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    DataTablePrefix table_prefix  
}
TableImageCrops {
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    string description  
    string biological_object  
    string compartment  
    DataFormat format  
    WarehouseNamespace namespace  
    ProfileLevel profile_level  
    DataTablePrefix table_prefix  
}
TableImageLabel {
    DataFormat data_format  
    AnalyzedDataRole data_role  
    LifecycleStage lifecycle_stage  
    uriorcurie ome_model_reference  
    string rembi_alignment  
    string description  
    string biological_object  
    string compartment  
    DataFormat format  
    WarehouseNamespace namespace  
    ProfileLevel profile_level  
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    DataTablePrefix table_prefix  
}
TableQualityControl {
    AnalyzedDataRole data_role  
    LifecycleStage lifecycle_stage  
    uriorcurie id  
    string name  
    string description  
    string biological_object  
    string compartment  
    DataFormat data_format  
    DataFormat format  
    WarehouseNamespace namespace  
    uriorcurie ome_model_reference  
    ProfileLevel profile_level  
    string rembi_alignment  
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    DataTablePrefix table_prefix  
}
TableSourceImages {
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    string description  
    string biological_object  
    string compartment  
    DataFormat format  
    WarehouseNamespace namespace  
    ProfileLevel profile_level  
    DataTablePrefix table_prefix  
}
Warehouse {
    uriorcurie id  
    string name  
    string description  
    uriorcurie ome_model_reference  
    string rembi_alignment  
    uriorcurie warehouse_root  
    SemVerString warehouse_spec_version  
}
WarehouseCatalog {
    uriorcurie id  
    string name  
    string description  
    string catalog_name  
    uriorcurie warehouse_root  
}
WarehouseImage {
    uriorcurie id  
    string name  
    string description  
    DataFormat data_format  
    uriorcurie ome_model_reference  
    uriorcurie path  
    string rembi_alignment  
}
WarehouseManifest {
    uriorcurie id  
    string name  
    string description  
    uriorcurie ome_model_reference  
    string rembi_alignment  
    uriorcurie warehouse_root  
    SemVerString warehouse_spec_version  
}
WarehouseTable {
    string description  
    string biological_object  
    string compartment  
    DataFormat format  
    WarehouseNamespace namespace  
    ProfileLevel profile_level  
    WarehouseTableRole role  
    TableIdentifier table_identifier  
    string table_name  
    DataTablePrefix table_prefix  
}

CatalogView ||--}o WarehouseImage : "view_images"
CatalogView ||--}o WarehouseTable : "source_tables"
ImageOMETiff ||--|o WarehouseManifest : "image_manifest"
ImageOMETiff ||--}o CatalogView : "image_views"
ImageOMEZarr ||--|o WarehouseManifest : "image_manifest"
ImageOMEZarr ||--}o CatalogView : "image_views"
ImageTIFF ||--|o WarehouseManifest : "image_manifest"
ImageTIFF ||--}o CatalogView : "image_views"
TableImageCrops ||--|o TableSourceImages : "source_image_table"
TableImageLabel ||--|o TableSourceImages : "source_image_table"
TableQualityControl ||--}o TableDerivedMeasurement : "related_measurement_tables"
TableQualityControl ||--}o TableEmbedding : "related_embedding_tables"
TableSourceImages ||--|o TableImageLabel : "label_table"
Warehouse ||--|o WarehouseManifest : "manifest"
Warehouse ||--}o WarehouseCatalog : "catalogs"
WarehouseCatalog ||--}o CatalogView : "views"
WarehouseCatalog ||--}o Namespace : "namespaces"
WarehouseImage ||--|o WarehouseManifest : "image_manifest"
WarehouseImage ||--}o CatalogView : "image_views"
WarehouseManifest ||--}o WarehouseImage : "manifest_images"
WarehouseManifest ||--}o WarehouseTable : "tables"
